service: prueba-tecnica-indra

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  starshipCollection: INDRA_STARSHIPS
  vehiclesCollection: INDRA_VEHICLES
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
 
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    STARSHIPS_COLLECTION: ${self:custom.starshipCollection}
    VEHICLES_COLLECTION: ${self:custom.vehiclesCollection}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getUser:
    handler: index.handler
    events:
      - http: 'GET /users/{proxy+}'
  createUser:
    handler: index.handler
    events:
      - http: 'POST /users'

resources:
  Resources:
    StarshipDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: naveId
            AttributeType: S
        KeySchema:
          -
            AttributeName: naveId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'INDRA_STARSHIPS'
    VehicleDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: naveId
            AttributeType: S
        KeySchema:
          -
            AttributeName: naveId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'INDRA_VEHICLES'